In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\AltFemp\raw_data\minning_data\pomelo_637.csv',sep=',')

In [3]:
df.head()

,note,estimated_heading,ch4_alive,anemometer_alive,co2_alive,rm_young_81000_alive,rm_young_86000_alive,gps_alive,gps_fix,spd_over_grnd,...,rmys_wdir_cf,rmys_wspd2D_cf,rmys_sonictemp,rmys_status,rmys_record_time,wdir_cf_corrected,wspd_cf_corrected,awdir_geo,true_wdir,true_wspd
0,NONE,263.71,1,1,0,0,1,1,1,0.022222,...,197.9,3.06,0.0,0,2018-11-14 07:28:06.820368,22.466634,2.783039,286.176634,286.176634,2.783039
1,NONE,263.70,1,1,0,0,1,1,1,0.005556,...,197.9,3.06,0.0,0,2018-11-14 07:28:06.820368,22.466634,2.783039,286.166634,286.166634,2.783039
2,NONE,263.72,1,1,0,0,1,1,1,0.030556,...,203.4,2.82,0.0,0,2018-11-14 07:28:06.929717,26.171106,2.588300,289.891106,289.891106,2.588300
3,NONE,263.71,1,1,0,0,1,1,1,0.052778,...,203.0,3.00,0.0,0,2018-11-14 07:28:07.023446,25.939360,2.751651,289.649360,289.649360,2.751651
4,NONE,263.72,1,1,0,0,1,1,1,0.052778,...,203.0,3.06,0.0,0,2018-11-14 07:28:07.132795,25.939360,2.806684,289.659360,289.659360,2.806684

In [5]:
df.shape

(10000, 72)

In [10]:
r = df.ch4_recordtime

In [11]:
r[0]

'2018-11-14 07:28:06.726640'

In [14]:
df.shape[0]

10000

In [15]:
len(r)

10000

In [17]:
r[10000-1]

'2018-11-14 07:43:44.760078'

In [19]:
range = pd.date_range(r[0], r[df.shape[0]-1], periods=df.shape[0])

In [20]:
range

DatetimeIndex(['2018-11-14 07:28:06.726640128',
               '2018-11-14 07:28:06.820452864',
               '2018-11-14 07:28:06.914265600',
               '2018-11-14 07:28:07.008078336',
               '2018-11-14 07:28:07.101891072',
               '2018-11-14 07:28:07.195703808',
               '2018-11-14 07:28:07.289516544',
               '2018-11-14 07:28:07.383329280',
               '2018-11-14 07:28:07.477142016',
               '2018-11-14 07:28:07.570954752',
               ...
               '2018-11-14 07:43:43.915763456',
               '2018-11-14 07:43:44.009576192',
               '2018-11-14 07:43:44.103388928',
               '2018-11-14 07:43:44.197201664',
               '2018-11-14 07:43:44.291014400',
               '2018-11-14 07:43:44.384827136',
               '2018-11-14 07:43:44.478639872',
               '2018-11-14 07:43:44.572452608',
               '2018-11-14 07:43:44.666265344',
               '2018-11-14 07:43:44.760078080'],
              dtype='datetime64[ns]', length=10000, freq=None)

In [22]:
df.index =range

In [23]:
df.head()

,note,estimated_heading,ch4_alive,anemometer_alive,co2_alive,rm_young_81000_alive,rm_young_86000_alive,gps_alive,gps_fix,spd_over_grnd,...,rmys_wdir_cf,rmys_wspd2D_cf,rmys_sonictemp,rmys_status,rmys_record_time,wdir_cf_corrected,wspd_cf_corrected,awdir_geo,true_wdir,true_wspd
2018-11-14 07:28:06.726640128,NONE,263.71,1,1,0,0,1,1,1,0.022222,...,197.9,3.06,0.0,0,2018-11-14 07:28:06.820368,22.466634,2.783039,286.176634,286.176634,2.783039
2018-11-14 07:28:06.820452864,NONE,263.70,1,1,0,0,1,1,1,0.005556,...,197.9,3.06,0.0,0,2018-11-14 07:28:06.820368,22.466634,2.783039,286.166634,286.166634,2.783039
2018-11-14 07:28:06.914265600,NONE,263.72,1,1,0,0,1,1,1,0.030556,...,203.4,2.82,0.0,0,2018-11-14 07:28:06.929717,26.171106,2.588300,289.891106,289.891106,2.588300
2018-11-14 07:28:07.008078336,NONE,263.71,1,1,0,0,1,1,1,0.052778,...,203.0,3.00,0.0,0,2018-11-14 07:28:07.023446,25.939360,2.751651,289.649360,289.649360,2.751651
2018-11-14 07:28:07.101891072,NONE,263.72,1,1,0,0,1,1,1,0.052778,...,203.0,3.06,0.0,0,2018-11-14 07:28:07.132795,25.939360,2.806684,289.659360,289.659360,2.806684

In [24]:
second_sum = pd.DataFrame()
second_sum['true_wspd'] = df.true_wspd.resample('S').mean()

In [25]:
second_sum

                     true_wspd
2018-11-14 07:28:06   2.718126
2018-11-14 07:28:07   2.535312
2018-11-14 07:28:08   2.746517
2018-11-14 07:28:09   3.048761
2018-11-14 07:28:10   3.026285
2018-11-14 07:28:11   2.661988
2018-11-14 07:28:12   3.079349
2018-11-14 07:28:13   3.148101
2018-11-14 07:28:14   2.781863
2018-11-14 07:28:15   2.487784
2018-11-14 07:28:16   2.458079
2018-11-14 07:28:17   3.049676
2018-11-14 07:28:18   3.155137
2018-11-14 07:28:19   2.640287
2018-11-14 07:28:20   2.563117
2018-11-14 07:28:21   2.138375
2018-11-14 07:28:22   2.198883
2018-11-14 07:28:23   2.236624
2018-11-14 07:28:24   2.376760
2018-11-14 07:28:25   2.494129
2018-11-14 07:28:26   2.395146
2018-11-14 07:28:27   2.327799
2018-11-14 07:28:28   2.305922
2018-11-14 07:28:29   2.123123
2018-11-14 07:28:30   2.113252
2018-11-14 07:28:31   2.123681
2018-11-14 07:28:32   1.828190
2018-11-14 07:28:33   2.051513
2018-11-14 07:28:34   2.428307
2018-11-14 07:28:35   2.470401
...                        ...
2018-11-14 07:43:15   2.443283
2018-11-14 07:43:16   2.525631
2018-11-14 07:43:17   2.553469
2018-11-14 07:43:18   2.484747
2018-11-14 07:43:19   2.491582
2018-11-14 07:43:20   2.398029
2018-11-14 07:43:21   2.118400
2018-11-14 07:43:22   2.181749
2018-11-14 07:43:23   2.168440
2018-11-14 07:43:24   2.109536
2018-11-14 07:43:25   2.206350
2018-11-14 07:43:26   2.341366
2018-11-14 07:43:27   2.452119
2018-11-14 07:43:28   2.548342
2018-11-14 07:43:29   2.508547
2018-11-14 07:43:30   2.392461
2018-11-14 07:43:31   2.332866
2018-11-14 07:43:32   1.978913
2018-11-14 07:43:33   1.939859
2018-11-14 07:43:34   2.030396
2018-11-14 07:43:35   2.347669
2018-11-14 07:43:36   2.195141
2018-11-14 07:43:37   1.884228
2018-11-14 07:43:38   1.937777
2018-11-14 07:43:39   1.956216
2018-11-14 07:43:40   1.938538
2018-11-14 07:43:41   2.085903
2018-11-14 07:43:42   2.189497
2018-11-14 07:43:43   2.395183
2018-11-14 07:43:44   2.468854

[939 rows x 1 columns]